version: '3'

services:
  docker-cosmos:
    container_name: cosmos_mainnet
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - MONIKER=NodeName
      - CHAIN_ID=cosmoshub-2
      - GENESIS_URL=https://raw.githubusercontent.com/cosmos/launch/master/genesis.json
      - SEEDS=b1c618b89f8f996b7d07e1df710a33e4e4e186c5@stakehedge.com:26656
      # - GAIAD_HOME=/.gaiad
      # - ADDR_BOOK_STRICT=false
      # - CACHE_SIZE=10000
    restart: always
    ports:
      - "26656:26656"
      - "26657:26657"
      - "26658:26658"
      - "1317:1317" # for rest-server
    volumes:
      - data:/.gaiad
volumes:
  data:
