version: '3'

services:
  docker-cosmos:
    container_name: nonamenode
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - MONIKER=NodeName
      - CHAIN_ID=cosmoshub-2
      # - GAIAD_HOME=/.gaiad
      # - GENESIS_URL=  leave commented out for default cosmoshub-2 (or give url of your choice)
    ports:
      - "26656:26656"
      - "26657:26657"
      - "26658:26658"
      - "1317:1317" # for rest-server
    volumes:
      - ./data/config:/.gaiad/config
      - ./data/keys:/.gaiacli/keys

